//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGroupe2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soin", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    public partial class Soin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float coutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoin {
            get {
                return this.IdSoinField;
            }
            set {
                if ((this.IdSoinField.Equals(value) != true)) {
                    this.IdSoinField = value;
                    this.RaisePropertyChanged("IdSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float cout {
            get {
                return this.coutField;
            }
            set {
                if ((this.coutField.Equals(value) != true)) {
                    this.coutField = value;
                    this.RaisePropertyChanged("cout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IIISoin")]
    public interface IIISoin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetListeSoins", ReplyAction="http://tempuri.org/IIISoin/GetListeSoinsResponse")]
        AppGroupe2.ServiceReference1.Soin[] GetListeSoins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetListeSoins", ReplyAction="http://tempuri.org/IIISoin/GetListeSoinsResponse")]
        System.Threading.Tasks.Task<AppGroupe2.ServiceReference1.Soin[]> GetListeSoinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/AddSoin", ReplyAction="http://tempuri.org/IIISoin/AddSoinResponse")]
        bool AddSoin(AppGroupe2.ServiceReference1.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/AddSoin", ReplyAction="http://tempuri.org/IIISoin/AddSoinResponse")]
        System.Threading.Tasks.Task<bool> AddSoinAsync(AppGroupe2.ServiceReference1.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/UpdateSoin", ReplyAction="http://tempuri.org/IIISoin/UpdateSoinResponse")]
        bool UpdateSoin(AppGroupe2.ServiceReference1.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/UpdateSoin", ReplyAction="http://tempuri.org/IIISoin/UpdateSoinResponse")]
        System.Threading.Tasks.Task<bool> UpdateSoinAsync(AppGroupe2.ServiceReference1.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/SupprimerSoin", ReplyAction="http://tempuri.org/IIISoin/SupprimerSoinResponse")]
        void SupprimerSoin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/SupprimerSoin", ReplyAction="http://tempuri.org/IIISoin/SupprimerSoinResponse")]
        System.Threading.Tasks.Task SupprimerSoinAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetSoinById", ReplyAction="http://tempuri.org/IIISoin/GetSoinByIdResponse")]
        AppGroupe2.ServiceReference1.Soin GetSoinById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetSoinById", ReplyAction="http://tempuri.org/IIISoin/GetSoinByIdResponse")]
        System.Threading.Tasks.Task<AppGroupe2.ServiceReference1.Soin> GetSoinByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIISoinChannel : AppGroupe2.ServiceReference1.IIISoin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IISoinClient : System.ServiceModel.ClientBase<AppGroupe2.ServiceReference1.IIISoin>, AppGroupe2.ServiceReference1.IIISoin {
        
        public IISoinClient() {
        }
        
        public IISoinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IISoinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IISoinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IISoinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppGroupe2.ServiceReference1.Soin[] GetListeSoins() {
            return base.Channel.GetListeSoins();
        }
        
        public System.Threading.Tasks.Task<AppGroupe2.ServiceReference1.Soin[]> GetListeSoinsAsync() {
            return base.Channel.GetListeSoinsAsync();
        }
        
        public bool AddSoin(AppGroupe2.ServiceReference1.Soin soin) {
            return base.Channel.AddSoin(soin);
        }
        
        public System.Threading.Tasks.Task<bool> AddSoinAsync(AppGroupe2.ServiceReference1.Soin soin) {
            return base.Channel.AddSoinAsync(soin);
        }
        
        public bool UpdateSoin(AppGroupe2.ServiceReference1.Soin soin) {
            return base.Channel.UpdateSoin(soin);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSoinAsync(AppGroupe2.ServiceReference1.Soin soin) {
            return base.Channel.UpdateSoinAsync(soin);
        }
        
        public void SupprimerSoin(int id) {
            base.Channel.SupprimerSoin(id);
        }
        
        public System.Threading.Tasks.Task SupprimerSoinAsync(int id) {
            return base.Channel.SupprimerSoinAsync(id);
        }
        
        public AppGroupe2.ServiceReference1.Soin GetSoinById(int id) {
            return base.Channel.GetSoinById(id);
        }
        
        public System.Threading.Tasks.Task<AppGroupe2.ServiceReference1.Soin> GetSoinByIdAsync(int id) {
            return base.Channel.GetSoinByIdAsync(id);
        }
    }
}
