//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGroupe2.ServiceSoin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soin", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    public partial class Soin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float coutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoin {
            get {
                return this.IdSoinField;
            }
            set {
                if ((this.IdSoinField.Equals(value) != true)) {
                    this.IdSoinField = value;
                    this.RaisePropertyChanged("IdSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float cout {
            get {
                return this.coutField;
            }
            set {
                if ((this.coutField.Equals(value) != true)) {
                    this.coutField = value;
                    this.RaisePropertyChanged("cout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppGroupe2.ServiceSoin.Patient))]
    public partial class Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdU {
            get {
                return this.IdUField;
            }
            set {
                if ((this.IdUField.Equals(value) != true)) {
                    this.IdUField = value;
                    this.RaisePropertyChanged("IdU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPrenom {
            get {
                return this.NomPrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPrenomField, value) != true)) {
                    this.NomPrenomField = value;
                    this.RaisePropertyChanged("NomPrenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    public partial class Patient : AppGroupe2.ServiceSoin.Personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateNaissanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupeSanguinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> PoidsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> TailleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateNaissance {
            get {
                return this.DateNaissanceField;
            }
            set {
                if ((this.DateNaissanceField.Equals(value) != true)) {
                    this.DateNaissanceField = value;
                    this.RaisePropertyChanged("DateNaissance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupeSanguin {
            get {
                return this.GroupeSanguinField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupeSanguinField, value) != true)) {
                    this.GroupeSanguinField = value;
                    this.RaisePropertyChanged("GroupeSanguin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Poids {
            get {
                return this.PoidsField;
            }
            set {
                if ((this.PoidsField.Equals(value) != true)) {
                    this.PoidsField = value;
                    this.RaisePropertyChanged("Poids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Taille {
            get {
                return this.TailleField;
            }
            set {
                if ((this.TailleField.Equals(value) != true)) {
                    this.TailleField = value;
                    this.RaisePropertyChanged("Taille");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSoin.IIISoin")]
    public interface IIISoin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetListeSoins", ReplyAction="http://tempuri.org/IIISoin/GetListeSoinsResponse")]
        AppGroupe2.ServiceSoin.Soin[] GetListeSoins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetListeSoins", ReplyAction="http://tempuri.org/IIISoin/GetListeSoinsResponse")]
        System.Threading.Tasks.Task<AppGroupe2.ServiceSoin.Soin[]> GetListeSoinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/AddSoin", ReplyAction="http://tempuri.org/IIISoin/AddSoinResponse")]
        bool AddSoin(AppGroupe2.ServiceSoin.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/AddSoin", ReplyAction="http://tempuri.org/IIISoin/AddSoinResponse")]
        System.Threading.Tasks.Task<bool> AddSoinAsync(AppGroupe2.ServiceSoin.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/UpdateSoin", ReplyAction="http://tempuri.org/IIISoin/UpdateSoinResponse")]
        bool UpdateSoin(AppGroupe2.ServiceSoin.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/UpdateSoin", ReplyAction="http://tempuri.org/IIISoin/UpdateSoinResponse")]
        System.Threading.Tasks.Task<bool> UpdateSoinAsync(AppGroupe2.ServiceSoin.Soin soin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/SupprimerSoin", ReplyAction="http://tempuri.org/IIISoin/SupprimerSoinResponse")]
        void SupprimerSoin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/SupprimerSoin", ReplyAction="http://tempuri.org/IIISoin/SupprimerSoinResponse")]
        System.Threading.Tasks.Task SupprimerSoinAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetSoinById", ReplyAction="http://tempuri.org/IIISoin/GetSoinByIdResponse")]
        AppGroupe2.ServiceSoin.Patient GetSoinById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIISoin/GetSoinById", ReplyAction="http://tempuri.org/IIISoin/GetSoinByIdResponse")]
        System.Threading.Tasks.Task<AppGroupe2.ServiceSoin.Patient> GetSoinByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIISoinChannel : AppGroupe2.ServiceSoin.IIISoin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IISoinClient : System.ServiceModel.ClientBase<AppGroupe2.ServiceSoin.IIISoin>, AppGroupe2.ServiceSoin.IIISoin {
        
        public IISoinClient() {
        }
        
        public IISoinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IISoinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IISoinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IISoinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppGroupe2.ServiceSoin.Soin[] GetListeSoins() {
            return base.Channel.GetListeSoins();
        }
        
        public System.Threading.Tasks.Task<AppGroupe2.ServiceSoin.Soin[]> GetListeSoinsAsync() {
            return base.Channel.GetListeSoinsAsync();
        }
        
        public bool AddSoin(AppGroupe2.ServiceSoin.Soin soin) {
            return base.Channel.AddSoin(soin);
        }
        
        public System.Threading.Tasks.Task<bool> AddSoinAsync(AppGroupe2.ServiceSoin.Soin soin) {
            return base.Channel.AddSoinAsync(soin);
        }
        
        public bool UpdateSoin(AppGroupe2.ServiceSoin.Soin soin) {
            return base.Channel.UpdateSoin(soin);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSoinAsync(AppGroupe2.ServiceSoin.Soin soin) {
            return base.Channel.UpdateSoinAsync(soin);
        }
        
        public void SupprimerSoin(int id) {
            base.Channel.SupprimerSoin(id);
        }
        
        public System.Threading.Tasks.Task SupprimerSoinAsync(int id) {
            return base.Channel.SupprimerSoinAsync(id);
        }
        
        public AppGroupe2.ServiceSoin.Patient GetSoinById(int id) {
            return base.Channel.GetSoinById(id);
        }
        
        public System.Threading.Tasks.Task<AppGroupe2.ServiceSoin.Patient> GetSoinByIdAsync(int id) {
            return base.Channel.GetSoinByIdAsync(id);
        }
    }
}
